version: "3.8"
services:

    # PHP service
    app:
        build: ./docker/php
        image: php
        container_name: php-AnonByte
        working_dir: /var/www/
        volumes:
            - ./project:/var/www
            - ./log/php:/srv/var/log
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql
        container_name: php-Mysql-AnonByte
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
        - "./mysql/:/var/lib/mysql"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin
        container_name: php-PhpMyAdmin-AnonByte
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8080:80
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx
        container_name: php-nginx-AnonByte
        ports:
            - 8000:80
        volumes:
            - ./project:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./log/nginx:/var/log/nginx/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
