version: "3.8"
services:

    # PHP service
    app:
        build: ./docker/php
        image: app
        container_name: app-AnonByte
        working_dir: /var/www/
        volumes:
            - ./project:/var/www
            - ./log/php:/srv/var/log
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:8.0
        container_name: Mysql-AnonByte
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
        - "./mysql/:/var/lib/mysql"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin
        container_name: PhpMyAdmin-AnonByte
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            PMA_ARBITRARY: 1
        env_file:
            - ./.env
        restart: always
        ports:
            - 8080:80
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx
        container_name: nginx-AnonByte
        ports:
            - 80:80
        volumes:
            - ./project:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./log/nginx:/var/log/nginx/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
